### ISSUE TITLE
Can't get past the hydraulic doors with Barney at the intro

### ISSUE THREAD

**Issue by Lesselpine** [IntriguingTiles/alien-mode#1]
I think Barney's ai breaks but idk

**Comment by IntriguingTiles** [comment]
Seems like an issue with the PS2 content since this doesn't occur when PS2 content is disabled. Looking into this now.

**Comment by IntriguingTiles** [comment]
[This has been fixed in Alien Mode 1.2](https://www.moddb.com/mods/alien-mode/downloads/alien-mode-12-patch). Thanks a ton for reporting this!
